### ISSUE TITLE
Failed to add URL ACL

### ISSUE THREAD

**Issue by karius-stack** [Funbit/ets2-telemetry-server#107]
So I have a small problem every time I install Ets2Telemetry. Because every time I set it up, it will fail on the ACL rule.

The error:
```
Url reservation add failed, Error: 6
The handle is invalid.
```

Ets2Telemetry Log:

```
2017-06-07 10:14:39,455 [1   ] [INFO ] Running application on Microsoft Windows NT 6.2.9200.0 (64-bit) 
2017-06-07 10:14:39,472 [1   ] [INFO ] Checking plugin DLL files...
2017-06-07 10:14:39,473 [1   ] [INFO ] Checking Firewall rule...
2017-06-07 10:14:39,475 [1   ] [INFO ] Running command line: 
netsh advfirewall firewall show rule dir=in name=all
2017-06-07 10:14:39,871 [1   ] [INFO ] Checking ACL rule status...
2017-06-07 10:14:39,871 [1   ] [INFO ] Running command line: 
netsh http show urlacl url=http://+:25555/
2017-06-07 10:14:39,925 [1   ] [ERROR] System.Exception: Failed to check URL ACL status: 
URL Reservations: 
----------------- 

The handle is invalid.



   at Funbit.Ets.Telemetry.Server.Helpers.ProcessHelper.RunNetShell(String arguments, String errorMessage)
   at Funbit.Ets.Telemetry.Server.Setup.UrlReservationSetup..ctor()
2017-06-07 10:14:41,797 [1   ] [INFO ] Running application on Microsoft Windows NT 6.2.9200.0 (64-bit) 
2017-06-07 10:14:41,814 [1   ] [INFO ] Checking plugin DLL files...
2017-06-07 10:14:41,815 [1   ] [INFO ] Checking Firewall rule...
2017-06-07 10:14:41,817 [1   ] [INFO ] Running command line: 
netsh advfirewall firewall show rule dir=in name=all
2017-06-07 10:14:42,211 [1   ] [INFO ] Checking ACL rule status...
2017-06-07 10:14:42,211 [1   ] [INFO ] Running command line: 
netsh http show urlacl url=http://+:25555/
2017-06-07 10:14:42,267 [1   ] [ERROR] System.Exception: Failed to check URL ACL status: 
URL Reservations: 
----------------- 

The handle is invalid.



   at Funbit.Ets.Telemetry.Server.Helpers.ProcessHelper.RunNetShell(String arguments, String errorMessage)
   at Funbit.Ets.Telemetry.Server.Setup.UrlReservationSetup..ctor()
2017-06-07 10:14:44,121 [1   ] [INFO ] Validating ETS2 path: 'd:\program files (x86)\steam\SteamApps\common\Euro Truck Simulator 2' ... OK
2017-06-07 10:14:44,121 [1   ] [INFO ] Copying ETS2 x86 plugin DLL file to: d:\program files (x86)\steam\SteamApps\common\Euro Truck Simulator 2\bin\win_x86\plugins\ets2-telemetry-server.dll
2017-06-07 10:14:44,185 [1   ] [INFO ] Copying ETS2 x64 plugin DLL file to: d:\program files (x86)\steam\SteamApps\common\Euro Truck Simulator 2\bin\win_x64\plugins\ets2-telemetry-server.dll
2017-06-07 10:14:44,238 [1   ] [INFO ] Validating ATS path: 'd:\program files (x86)\steam\SteamApps\common\American Truck Simulator' ... Fail
2017-06-07 10:14:44,240 [1   ] [INFO ] Validating ATS path: 'd:\program files (x86)\steam\SteamApps\common\American Truck Simulator' ... Fail
2017-06-07 10:14:45,714 [1   ] [INFO ] Adding Firewall rule...
2017-06-07 10:14:45,714 [1   ] [INFO ] Running command line: 
netsh advfirewall firewall add rule name="ETS2 TELEMETRY SERVER (PORT 25555)" dir=in action=allow protocol=TCP localport=25555 remoteip=localsubnet
2017-06-07 10:14:45,787 [1   ] [INFO ] Adding ACL rule...
2017-06-07 10:14:45,787 [1   ] [INFO ] Running command line: 
netsh http add urlacl url=http://+:25555/ user="\Everyone"
2017-06-07 10:14:45,848 [1   ] [ERROR] System.Exception: Failed to add URL ACL: 
Url reservation add failed, Error: 6
The handle is invalid.



   at Funbit.Ets.Telemetry.Server.Helpers.ProcessHelper.RunNetShell(String arguments, String errorMessage)
   at Funbit.Ets.Telemetry.Server.Setup.UrlReservationSetup.Install(IWin32Window owner)
2017-06-07 10:14:45,855 [1   ] [ERROR] System.Exception: Failed to add URL ACL: 
Url reservation add failed, Error: 6
The handle is invalid.
```

Does anyone know what I can do to fix this?

**Comment by ColinM9991-zz** [comment]
Run it as an administrator
